START
GET FIRST NUMBER 
GET SECOND NUMBER 
PRINT FIRST NUMBER + SECOND NUMBER 
PRINT FIRST NUMBER - SECOND NUMBER 
PRINT FIRST NUMBER * SECOND NUMBER
PRINT FIRST NUMBER/ SECOND NUMBER 
DISPLAY RESULT
STOP
